apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab-platform
  namespace: argocd
spec:
  description: "Projet GitOps - Lab Plateforme DevSecOps"
  sourceRepos:
    - "*"                         # Tous les repos GitLab du lab
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
