# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "my-bucket-maxto-platform.cloud"
    key    = "infrastructure/terraform.tfstate"
    region = "eu-west-3"
  }
}
