apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-secret
  namespace: app-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"registry.gitlab.com":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: app-demo/gitlab-registry
        property: username
    - secretKey: password
      remoteRef:
        key: app-demo/gitlab-registry
        property: password
