apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: js-game-app
  namespace: js-game
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: js-game-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
