{
 "title": "app-demo",
 "tags": [
  "app-demo",
  "gitops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requêtes HTTP / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_demo_http_requests_total[1m])) by (endpoint, status)",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latence P99 / P50 (secondes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_demo_http_duration_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "p99 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_demo_http_duration_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "p50 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total requêtes (compteur)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(app_demo_http_requests_total)"
    }
   ]
  },
  {
   "title": "Taux d'erreurs 5xx",
   "type": "stat",
   "gridPos": { "x": 6, "y": 8, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(app_demo_http_requests_total{status=~\"5..\"}[5m])) / sum(rate(app_demo_http_requests_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Répartition par endpoint",
   "type": "piechart",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(app_demo_http_requests_total[1h])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Version de l'application",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_demo_info",
     "legendFormat": "v{{version}} — built {{build_time}}"
    }
   ]
  }
 ]
}